/**
   GeekFactory - "INNOVATING TOGETHER"
   Distribucion de materiales para el desarrollo e innovacion tecnologica
   www.geekfactory.mx
 
   EJEMPLO BASICO PARA EL USO DEL LCD 16X2 CON ARDUINO. MUESTRA UN TEXTO QUE RECORRE
   LA PANTALLA DE UN LADO A OTRO. ESTE PROGRAMA SIRVE COMO PRUEBA DEL CORRECTO
   FUNCIONAMIENTO DE NUESTRO CONEXIONADO Y TAMBIEN ILUSTRA COMO REALIZAR OPERACIONES
   CON EL CURSOR, BORRAR LA PANTALLA Y MOSTRAR CADENAS DE TEXTO.
*/
#include  <LiquidCrystal.h>
 
// CONSTRUCTOR PARA LA PANTALLA LCD 16X2
// AQUI SE CONFIGURAN LOS PINES PARA LA COMUNICACION CON LA PANTALLA
LiquidCrystal lcd(12, 11, 5, 4, 3, 2);
 
void setup()
{
  // INDICAMOS QUE TENEMOS CONECTADA UNA PANTALLA DE 16X2
  lcd.begin(16, 2);
  // MOVER EL CURSOR A LA PRIMERA POSICION DE LA PANTALLA Y BORRAR (0, 0)
  lcd.clear();
  // IMPRIMIR CADENA EN LA PRIMERA POSICION
  lcd.print(" GEEKFACTORY.MX ");
  // ESPERAR UN SEGUNDO
  delay(1000);
}
 
void loop()
{
  // BORRAMOS TODA LA PANTALLA PARA ACTUALIZARLA CADA SEGUNDO
  lcd.clear();
  // IMPRIMIR UN ENCABEZADO
  lcd.print(" POTENCIOMETRO  ");
 
  // REALIZAR LECTURA ANALOGICA EN PIN A0
  unsigned int val = analogRead(A0);
  // CONVERTIR ESE VALOR A VOLTAJE (ASUMIENDO QUE EL ARDUINO SE ALIMENTA A 5 VOLTS)
  float volts = (val * 5.0) / 1024.0;
 
  // IMPRIMIR VALORES EN LA SEGUNDA LINEA, COMENZANDO POR EL VALOR DIRECTO DEL ADC
  lcd.setCursor(0, 1);
  lcd.print(val);
 
  // IMPRIMIR EL VALOR EN VOLTAJE, DESPUES DE LA LECTURA DEL ADC
  lcd.setCursor(6, 1);
  lcd.print(volts, 1);
 
  // ESPERAR UN SEGUNDO ANTES DE CONTUNUAR
  delay (1000);
}
